version: '3'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-15T01-07-19Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioTopSecret
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-d" ,"postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning  --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis_data:/var/lib/redis/data

  booking-service:
    image: ghcr.io/lovehotel24/booking-service:latest
    environment:
      - BOOK_PG_USER=postgres
      - BOOK_PG_PASS=postgres
      - BOOK_PG_HOST=postgres
      - BOOK_PG_DB=postgres
      - BOOK_PORT=8081
      - BOOK_GRPC_PORT=50051
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  room-service:
    image: ghcr.io/lovehotel24/room-service:latest
    environment:
      - ROOM_PG_HOST=postgres
      - ROOM_PG_USER=postgres
      - ROOM_PG_PASS=postgres
      - ROOM_PG_DB=postgres
      - ROOM_PORT=8080
      - ROOM_GRPC_HOST=booking-service:50051
      - ROOM_BUCKET=room
      - ROOM_S3_URL=http://localhost:9000
      - ACCESS_KEY=minio
      - SECRET_KEY=minioTopSecret
    ports:
      - "8082:8082"
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      booking-service:
        condition: service_started

volumes:
  postgres-data:
  redis_data:
  minio_data: